version: "3.4"

services:
  db-mysql:
    image: mysql:5.7
    volumes:
      - ./scripts/user.sql:/docker-entrypoint-initdb.d/create_users.sql
      - ./volumes/data/mysql/:/var/lib/mysql
      - ./configs/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "calendar"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
